#####  The Numpy reshape function

Its common to find reshape errors when working with Machine Learning. This is owing to the fact that some of the libraries expect us to provide with a multi-dimensional array or an array of specific dimension as input. In such events we need to reshape our input array. Its better to understand the reshape function as this will help us achieve the reshaping easily. 

In [15]:
import numpy as np

In [31]:
a = np.arange(8)
print(a.shape)
print(a)

a = a.reshape(-1,1)
print(a.shape)
print(a)

a = a.reshape(1,-1)
print(a.shape)
print(a)

a = a.ravel()
#a = a.reshape(-1)
print(a.shape)
print(a)

(8,)
[0 1 2 3 4 5 6 7]
(8, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
(1, 8)
[[0 1 2 3 4 5 6 7]]
(8,)
[0 1 2 3 4 5 6 7]


In [28]:
b = np.array([[1, 2, 4], [5, 6, 7]])
print(b.shape)
print(b)

b = b.reshape(3,-1)
print(b.shape)
print(b)

b = b.reshape(-1,6)
print(b.shape)
print(b)

(2, 3)
[[1 2 4]
 [5 6 7]]
(3, 2)
[[1 2]
 [4 5]
 [6 7]]
(1, 6)
[[1 2 4 5 6 7]]
